name: C/C++ CI w/cmake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir workflow && cd workflow && cmake ..
    - name: build
      run: cmake --build workflow
#    - name: test
#      run: cd workflow && ctest

  build-windows:

    runs-on: windows-latest
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [windows-latest, windows-2016]
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir workflow && cd workflow && cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..
    - name: build
      run: cmake --build workflow
#    - name: test
#      run: cd workflow && ctest
