name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir workflow && cd workflow && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: build
      run: cmake --build workflow
    - name: test
      run: cd workflow && ctest

  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, windows-2016]
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir workflow && cd workflow && cmake ..
    - name: build
      run: cmake --build workflow --config Debug
    - name: test
      run: cd workflow && ctest
